set(CMAKE_SYSTEM_NAME QNX)
set(CMAKE_SYSTEM_PROCESSOR aarch64)
set(QNX_PROCESSOR aarch64)
set(QNX_TARGET_ARCH aarch64le)

set(CMAKE_C_COMPILER   qcc)
set(CMAKE_CXX_COMPILER q++)

set(CMAKE_C_COMPILER_TARGET   gcc_ntoaarch64le)
set(CMAKE_CXX_COMPILER_TARGET gcc_ntoaarch64le)

set(CMAKE_SYSROOT $ENV{QNX_TARGET})

list(APPEND CMAKE_FIND_ROOT_PATH /home/yasmine/qt6-qnx)

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY BOTH)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE BOTH)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE BOTH)