/* USER CODE BEGIN Header */
/**
 ******************************************************************************
 * @file           : main.c
 * @brief          : Main program body — SPI slave, single-transfer protocol
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 *
 * PROTOCOL (single-transfer, no command byte)
 * -------------------------------------------
 * The RPi master asserts CS and clocks out sizeof(stm32_data_t) = 15 dummy
 * bytes in one transaction.  The STM32 simultaneously shifts out a fresh
 * stm32_data_t struct.  There is no command byte and no two-phase handshake,
 * so there is no inter-phase race condition.
 *
 * The slave stays permanently armed: HAL_SPI_TxRxCpltCallback() calls
 * fill_test_data() to refresh the TX buffer and immediately re-arms
 * HAL_SPI_TransmitReceive_DMA(), so the next master transaction always finds
 * the peripheral ready.
 *
 * FIXES applied vs. previous IT version:
 *   1. NSS = SPI_NSS_HARD_INPUT (SSM=0) in MX_SPI2_Init().
 *      The STM32 SPI peripheral now gates byte-counting on the physical NSS
 *      pin.  Without this the peripheral ignores CS entirely (SSM=1) and
 *      clocks bytes continuously, causing the 4-frame misalignment pattern.
 *   2. HAL_SPI_TransmitReceive_DMA replaces _IT.
 *      DMA re-arm latency is ~nanoseconds vs. ~microseconds for IT, closing
 *      the window where MISO goes idle between callback and re-arm.
 */
/* USER CODE END Header */

/* Includes ------------------------------------------------------------------*/
#include "main.h"
#include "spi.h"
#include "gpio.h"
#include "dma.h"
#include <string.h>

/* Private includes ----------------------------------------------------------*/
/* USER CODE BEGIN Includes */
/* USER CODE END Includes */

/* Private typedef -----------------------------------------------------------*/
/* USER CODE BEGIN PTD */

/* ─────────────────────────────────────────────────────────────────────────
 * stm32_data_t — must EXACTLY match the RPi5 side:
 *   same field order, same types, same packing, same total size (15 bytes).
 *
 *   Verification:
 *     static_assert(sizeof(stm32_data_t) == 15, "struct size mismatch");
 * ───────────────────────────────────────────────────────────────────────── */
#pragma pack(push, 1)
typedef struct
{
    uint16_t field1; /* e.g. sensor A raw ADC          */
    uint16_t field2; /* e.g. sensor B raw ADC          */
    int16_t  field3; /* e.g. signed temperature × 10  */
    uint16_t field4; /* e.g. voltage × 100 mV          */
    uint8_t  field5; /* e.g. status flags              */
    uint16_t field6; /* e.g. RPM                        */
    uint32_t field7; /* e.g. millisecond timestamp     */
} stm32_data_t;
#pragma pack(pop)

/* Compile-time size guard — catches any accidental padding on either side.
 * _Static_assert is a C11 keyword; no header required. */
_Static_assert(sizeof(stm32_data_t) == 15, "stm32_data_t must be exactly 15 bytes");

/* USER CODE END PTD */

/* Private define ------------------------------------------------------------*/
/* USER CODE BEGIN PD */
/* USER CODE END PD */

/* Private macro -------------------------------------------------------------*/
/* USER CODE BEGIN PM */
/* USER CODE END PM */

/* Private variables ---------------------------------------------------------*/

/* USER CODE BEGIN PV */

/* SPI handle generated by CubeMX — adjust if you used a different instance */
extern SPI_HandleTypeDef hspi2;
#define SLAVE_SPI_HANDLE (&hspi2)

/* ─── TX buffer ─────────────────────────────────────────────────────────────
 * g_tx_data is the DMA source — it MUST remain valid for the full duration
 * of the transfer.  Declared static (not on the stack) to guarantee this.
 * fill_test_data() writes it only from HAL_SPI_TxRxCpltCallback(), which
 * fires after DMA completes, so there is no write/read overlap.
 *
 * If your MCU requires DMA buffers in a specific RAM region (e.g. SRAM1 on
 * STM32H7), add  __attribute__((section(".dma_buffer")))  here and configure
 * the linker script accordingly.  Not needed for STM32F4.
 * ─────────────────────────────────────────────────────────────────────────── */
static volatile stm32_data_t g_tx_data;

/* Dummy sink for the master's outgoing bytes — we don't use them */
static uint8_t g_rx_sink[sizeof(stm32_data_t)];

/* Diagnostics */
static volatile uint32_t g_transfer_count = 0; /* completed transfers */
static volatile uint32_t g_error_count    = 0; /* HAL errors seen     */

/* USER CODE END PV */

/* Private function prototypes -----------------------------------------------*/
void SystemClock_Config(void);

/* USER CODE BEGIN PFP */
static void fill_test_data(void);
static void arm_transfer(void);
/* USER CODE END PFP */

/* USER CODE BEGIN 0 */

/* ═══════════════════════════════════════════════════════════════════════════
 *  fill_test_data()
 *
 *  Refresh g_tx_data with "live" values.
 *  Called from arm_transfer() before every re-arm, so each master read
 *  gets an up-to-date snapshot.
 * ═══════════════════════════════════════════════════════════════════════════ */
static void fill_test_data(void)
{
    g_tx_data.field1 = (uint16_t)(1000 + g_transfer_count); /* counts up      */
    g_tx_data.field2 = 2000;
    g_tx_data.field3 = -250;                                 /* e.g. -25.0 °C  */
    g_tx_data.field4 = 3300;                                 /* e.g. 3.300 V   */
    g_tx_data.field5 = 0x01;                                 /* status flags   */
    g_tx_data.field6 = 1500;                                 /* RPM            */
    g_tx_data.field7 = HAL_GetTick();                        /* ms uptime      */
}

/* ═══════════════════════════════════════════════════════════════════════════
 *  arm_transfer()
 *
 *  Refresh TX data, then arm a single sizeof(stm32_data_t) DMA transfer.
 *  Call once at init and once at the end of every TxRxCpltCallback.
 *
 *  Using DMA (not IT) keeps the re-arm latency in the nanosecond range,
 *  so there is virtually no idle window on MISO between transfers.
 *
 *  REQUIREMENT: MX_DMA_Init() must be called before MX_SPI2_Init() in
 *  main() — CubeMX does this automatically when DMA is enabled for SPI2.
 * ═══════════════════════════════════════════════════════════════════════════ */
static void arm_transfer(void)
{
    fill_test_data();
    memset(g_rx_sink, 0, sizeof(g_rx_sink));

    // Call this ONCE. The circular DMA will keep it alive forever.
    HAL_StatusTypeDef status =
        HAL_SPI_TransmitReceive_DMA(SLAVE_SPI_HANDLE,
                                    (uint8_t *)&g_tx_data,
                                    g_rx_sink,
                                    sizeof(stm32_data_t));

}

/* ═══════════════════════════════════════════════════════════════════════════
 *  HAL_SPI_TxRxCpltCallback()
 *
 *  Fires when the DMA-driven TransmitReceive finishes (all 15 bytes sent
 *  and received).  Same callback name as the IT version — HAL uses it for
 *  both modes.  We count the transfer and immediately re-arm.
 *
 *  CubeMX declares a weak stub in stm32xxxx_it.c.  If you already have a
 *  non-weak definition there, merge this body into it.
 * ═══════════════════════════════════════════════════════════════════════════ */
void HAL_SPI_TxRxCpltCallback(SPI_HandleTypeDef *hspi)
{
    if (hspi->Instance != SLAVE_SPI_HANDLE->Instance)
        return;

    g_transfer_count++;

    /* * ONLY update the data. The DMA hardware has already wrapped 
     * around and is ready to send this fresh data on the next clock.
     */
    fill_test_data(); 
}

/* ═══════════════════════════════════════════════════════════════════════════
 *  HAL_SPI_ErrorCallback()
 *
 *  Fires on overrun, CRC, mode-fault, or DMA errors.  We abort any
 *  in-flight DMA, clear the overrun flag, then re-arm.
 *
 *  HAL_SPI_DMAStop() is safe to call even if no DMA is active.
 * ═══════════════════════════════════════════════════════════════════════════ */
void HAL_SPI_ErrorCallback(SPI_HandleTypeDef *hspi)
{
    if (hspi->Instance != SLAVE_SPI_HANDLE->Instance)
    {
        return;
    }

    g_error_count++;

    /* Stop any in-flight DMA streams before touching the peripheral */
    HAL_SPI_DMAStop(hspi);

    /* Clear overrun — mandatory before the next TransmitReceive arm */
    __HAL_SPI_CLEAR_OVRFLAG(hspi);

    arm_transfer();
}

/* USER CODE END 0 */

/* ═══════════════════════════════════════════════════════════════════════════
 *  main()
 * ═══════════════════════════════════════════════════════════════════════════ */
int main(void)
{
    HAL_Init();
    SystemClock_Config();
    MX_GPIO_Init();
    MX_DMA_Init();   /* MUST come before MX_SPI2_Init — DMA clocks must be
                      * enabled before the SPI peripheral binds its streams. */
    MX_SPI2_Init();  /* CubeMX-generated; ensure it sets:
                      *   hspi2.Init.NSS = SPI_NSS_HARD_INPUT  (SSM=0)
                      * If CubeMX generated SPI_NSS_SOFT, change it in the
                      * CubeMX GUI (SPI2 → Parameter Settings →
                      * NSS Signal Type → Hardware NSS Input Signal) and
                      * re-generate, or edit the Init struct directly here. */

    /* Arm the very first transfer — slave is now ready before the master
     * sends anything.  All subsequent re-arms happen inside the callback. */
    arm_transfer();

    while (1)
    {
        /* Nothing to do in the main loop.
         * All SPI work happens in HAL_SPI_TxRxCpltCallback().
         * You can add LED heartbeats, UART logging, etc. here. */
    }
}

/* ═══════════════════════════════════════════════════════════════════════════
 *  SystemClock_Config()  — generated by CubeMX, do not edit by hand
 * ═══════════════════════════════════════════════════════════════════════════ */
void SystemClock_Config(void)
{
    RCC_OscInitTypeDef osc = {0};
    RCC_ClkInitTypeDef clk = {0};
 
    /* Scale 2 is required to reach 84 MHz on the F401. */
    __HAL_RCC_PWR_CLK_ENABLE();
    __HAL_PWR_VOLTAGESCALING_CONFIG(PWR_REGULATOR_VOLTAGE_SCALE2);
 
    /* HSI on, PLL on. PLLQ=7 -> 48 MHz (only matters if you use USB OTG/SDIO,
     * but it must still be a valid divider). */
    osc.OscillatorType      = RCC_OSCILLATORTYPE_HSI;
    osc.HSIState            = RCC_HSI_ON;
    osc.HSICalibrationValue = RCC_HSICALIBRATION_DEFAULT;
    osc.PLL.PLLState        = RCC_PLL_ON;
    osc.PLL.PLLSource       = RCC_PLLSOURCE_HSI;
    osc.PLL.PLLM            = 16;
    osc.PLL.PLLN            = 336;
    osc.PLL.PLLP            = RCC_PLLP_DIV4;
    osc.PLL.PLLQ            = 7;
    if (HAL_RCC_OscConfig(&osc) != HAL_OK) {
        Error_Handler();                /* don't silently run at the wrong clock */
    }
 
    /* Switch SYSCLK to the PLL and set the bus prescalers.
     * AHB /1 = 84, APB1 /2 = 42 (must be <= 42), APB2 /1 = 84.
     * FLASH_LATENCY_2 is applied here, before the clock is raised. */
    clk.ClockType      = RCC_CLOCKTYPE_HCLK   | RCC_CLOCKTYPE_SYSCLK
                       | RCC_CLOCKTYPE_PCLK1  | RCC_CLOCKTYPE_PCLK2;
    clk.SYSCLKSource   = RCC_SYSCLKSOURCE_PLLCLK;
    clk.AHBCLKDivider  = RCC_SYSCLK_DIV1;
    clk.APB1CLKDivider = RCC_HCLK_DIV2;
    clk.APB2CLKDivider = RCC_HCLK_DIV1;
    if (HAL_RCC_ClockConfig(&clk, FLASH_LATENCY_2) != HAL_OK) {
        Error_Handler();
    }
 
    /* After this, SystemCoreClock == 84000000. Anything that latched a timing
     * value off the old 16 MHz (e.g. a cached SystemCoreClock, UART baud, or a
     * TIM prescaler computed earlier) must be re-derived from 84 MHz. */
}


/* USER CODE BEGIN 4 */
/* USER CODE END 4 */

void Error_Handler(void)
{
    /* USER CODE BEGIN Error_Handler_Debug */
    __disable_irq();
    while (1)
    {
    }
    /* USER CODE END Error_Handler_Debug */
}

#ifdef USE_FULL_ASSERT
void assert_failed(uint8_t *file, uint32_t line)
{
    /* USER CODE BEGIN 6 */
    (void)file;
    (void)line;
    /* USER CODE END 6 */
}
#endif /* USE_FULL_ASSERT */